name: Build & Push PySpark Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to GHCR
        if: env.REGISTRY == 'ghcr.io'
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ vars.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_REGISTRY_PAT }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6.18.0
        env:
          REPO_NAME: ${{ vars.GH_CONTAINER_REPO }}
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
